apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-mutating-webhook
webhooks:
  - name: pod-mutator.example.com
    clientConfig:
      url: "https://localhost:8443/"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lVWUp5cHM0ZjVCZGJiVEU1ZnZtanNJMDV3NTJvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNQjRYRFRJMU1Ea3dPVEUxTVRZeE9Gb1hEVEkyTURrdwpPVEUxTVRZeE9Gb3dGREVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdS9hcWdscUgvbnBxM2YvcXlDR2IrOUd6bVBWVEJFK1VuallkdnByZVB5elgKeDNTLzFsZ24vWEF6WERxbnFRWFJoODRzVmpxRXU0bDIveWVnYzBFcjBoQ2ZOSEhsbmExc2ZsalVvT2hUY0UyeAorR1EwYlZQSG5kb3NESFp1Szhpc1ZLcXpoZGRzK2dqbDV3WE1KTkx5Rzh1akN2KzcrODNxdHdLUlh3dXVKRlhaClBVZk9ZbTJXaUNlZWR5bmFKcnZFV2xIVmNoK3Z5Wkw1MEJOVGVuVWlxeE1FMWNqMmJOVVRDcTg2c3RXU2Rla24KYytKZ0p5a296akVrdUdidUd6Q21NZmJ4QWVQa2g2RjZHcDlkbHM4c0grNTg2MDhwcVFDWnBvS3dObzYvcFpRcApkUXhRZzlaQ2lKbkJERmhiWUdyeHhJUHpYS1lHeHVwUHQwUW9iY09DblFJREFRQUJvMjh3YlRBZEJnTlZIUTRFCkZnUVVxK0NJSmxZYzhwdzlNcjZ3em1GZlo2cHFmbHN3SHdZRFZSMGpCQmd3Rm9BVXErQ0lKbFljOHB3OU1yNncKem1GZlo2cHFmbHN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFhQmdOVkhSRUVFekFSZ2dsc2IyTmhiR2h2YzNTSApCSDhBQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJZjk4dS83OTRuajlrczZSaVpoY2ZibE8vdjhKRTlsCmtiMlZheTdRUk9aWVQxa09YT1JqWFpyR2FZanpGLzh0bzFCWmpBd2xXRE1vaE1GaFI0ZUJIL1BrYXV2L0xyaHUKVHYxd1cyVFppSlI0YTJ0NnhQY01tak1WbXR3dmVKMGFuZlJCU25VcU5sdkpXS0dQbnBMR2hOTGowR1llNU9BUgpLMkpjeEFXYW1ZNGZZRHBhRGdrZWphTlYxUlR6eVhXNkw0WmUrYjk0bnJvQ25jV0VjNVZDNFl1M0Iya1hoTXZjCktjbWludE91N2FYQVdkMTFFQ1JNWVFJY1J1S1FGNkVLbThabGppRCt6VzM2cjVYMDFtMG1jamJXbjRXOTZYU28KSWNLcWRsNkpkaDZ4d0R5TGo4Sm9KejdsbjlPNnJkRE4yQ3h5Smk4RFdJcXFoMmpTOGVwcEdjTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
